### PR TITLE
chore(cd): fix clean script for cd

### PR DESCRIPTION
**Pull request by yomarion**
## Description of the changes

This fixes the issue introduced by #1328 , when running `next-release` as part of the CI.

Partial view of the problem:
```
> @requestnetwork/data-format:clean

$ shx rm -rf dist tsconfig.tsbuildinfo tsconfig.build.tsbuildinfo
rm: no such file or directory: tsconfig.tsbuildinfo
```

### CODE REVIEW

**Review by benjlevesque — APPROVED** [review]

**Review by alexandre-abrioux — APPROVED** [review]

**Comment by benjlevesque** [comment]
I don't think the issue comes from #1328, but from #1237

**Comment by benjlevesque** [comment]
still not 😅 
actually #1333

**Comment by yomarion** [comment]
> still not 😅 actually #1333

@benjlevesque of course! The previous one failed to build so it's a different issue. I was looking for the lerna change from previous commits but it's not in the name. Thanks.

**Comment by benjlevesque** [comment]
what's strange is that the file missing is in `data-format`, which is a good argument for https://github.com/RequestNetwork/requestNetwork/pull/1328, but the build and released worked

**Pull request merged**
