### PR TITLE
chore(currency): export AggregatorsMap

### PR DESCRIPTION
**Pull request by yomarion**
## Description of the changes
AggregatorsMap is used by CurrencyManager constructor, so it should be exported.

### CODE REVIEW

**Review by bertux — APPROVED** [review]
good renaming

**Review by AdamDowson — APPROVED** [review]

**Comment by alexandre-abrioux** [comment]
@yomarion @benjlevesque Should the `AggregatorsMap` type be moved to the `types` package if it's used across packages? Asking because not sure if we strictly follow this logic for all types.

**Comment by benjlevesque** [comment]
hmm maybe 🤔. I have mixed feelings about the `types` package... For some abstractions it's useful to share interfaces, but for types like this, I don't know. I'm not against it anyway...

**Comment by alexandre-abrioux** [comment]
+1

**Pull request merged**
